version: '3.8'
services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - todo-network

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    networks:
      - todo-network
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - todo-network

volumes:
  db_data:

networks:
  todo-network:
    driver: bridge
